Renamed `struct request` in kinect2.c:55:8 to `struct requestPacket`
In `include/linux/blkdev.h:118:8` there is already a definition of `struct request`
which causes the compilation error of "redefination struct request".
Renaming variable to a more verbose name fixes the issue. No other
logic changes needed to fix this particular compilation issue.